var navContentDate =[
	[
		{
			url:"https://.kauzhu.com",
			src:"img/p1.jpg",
			name:"小米9",
			price:2999,
			tag:"新品"
		},
		{
			url:"https://.kauzhu.com",
			src:"img/p1.jpg",
			name:"小米9",
			price:2999,
			tag:"热卖",
		}
	],
	[
		{
			url:"https://.kauzhu.com",
			src:"img/p2.jpg",
			name:"小米9",
			price:2999,
			tag:"新品"
		},
		{
			url:"https://.kauzhu.com",
			src:"img/p1.jpg",
			name:"小米9",
			price:2999,
			tag:"热卖",
		}
	],
	[
		{
			url:"https://.kauzhu.com",
			src:"img/p1.jpg",
			name:"小米9",
			price:2999,
			tag:"新品"
		},
		{
			url:"https://.kauzhu.com",
			src:"img/p1.jpg",
			name:"小米9",
			price:2999,
			tag:"热卖",
		}
	],
	[
		{
			url:"https://.kauzhu.com",
			src:"img/p2.jpg",
			name:"小米9",
			price:2999,
			tag:"新品"
		},
		{
			url:"https://.kauzhu.com",
			src:"img/p1.jpg",
			name:"小米9",
			price:2999,
			tag:"热卖",
		},
		{
			url:"https://.kauzhu.com",
			src:"img/p1.jpg",
			name:"小米9",
			price:2999,
			tag:"热卖",
		},
		{
			url:"https://.kauzhu.com",
			src:"img/p1.jpg",
			name:"小米9",
			price:2999,
			tag:"热卖",
		}
	],
	[
		{
			url:"https://.kauzhu.com",
			src:"img/p2.jpg",
			name:"小米9",
			price:2999,
			tag:"新品"
		},
		{
			url:"https://.kauzhu.com",
			src:"img/p1.jpg",
			name:"小米9",
			price:2999,
			tag:"热卖",
		}
	],
	[
		{
			url:"https://.kauzhu.com",
			src:"img/p1.jpg",
			name:"小米9",
			price:2999,
			tag:"新品"
		},
		{
			url:"https://.kauzhu.com",
			src:"img/p1.jpg",
			name:"小米9",
			price:2999,
			tag:"热卖",
		}
	],
	[
		{
			url:"https://.kauzhu.com",
			src:"img/p2.jpg",
			name:"小米9",
			price:2999,
			tag:"新品"
		},
		{
			url:"https://.kauzhu.com",
			src:"img/p1.jpg",
			name:"小米9",
			price:2999,
			tag:"热卖",
		},
		{
			url:"https://.kauzhu.com",
			src:"img/p1.jpg",
			name:"小米9",
			price:2999,
			tag:"热卖",
		},
		{
			url:"https://.kauzhu.com",
			src:"img/p1.jpg",
			name:"小米9",
			price:2999,
			tag:"热卖",
		}
	],
	[
		{
			url:"https://.kauzhu.com",
			src:"img/p2.jpg",
			name:"小米9",
			price:2999,
			tag:"新品"
		},
		{
			url:"https://.kauzhu.com",
			src:"img/p1.jpg",
			name:"小米9",
			price:2999,
			tag:"热卖",
		},
		{
			url:"https://.kauzhu.com",
			src:"img/p1.jpg",
			name:"小米9",
			price:2999,
			tag:"热卖",
		},
		{
			url:"https://.kauzhu.com",
			src:"img/p1.jpg",
			name:"小米9",
			price:2999,
			tag:"热卖",
		}
	]
]


var cateItemDate =[
	[
		{
			url:"https://www.kauzhu.com",
			src:"img/p1.jpg",
			name:"小米9",
		},
		{
			url:"https://www.kauzhu.com",
			src:"img/p2.jpg",
			name:"小米9",
		}
	],
	[
		{
			url:"https://www.kauzhu.com",
			src:"img/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.kauzhu.com",
			src:"img/p2.jpg",
			name:"小米9"
		},
		{
			url:"https://www.kauzhu.com",
			src:"img/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.kauzhu.com",
			src:"img/p2.jpg",
			name:"小米9"
		},
		{
			url:"https://www.kauzhu.com",
			src:"img/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.kauzhu.com",
			src:"img/p2.jpg",
			name:"小米9"
		}
	],
	[
		{
			url:"https://www.kauzhu.com",
			src:"img/p1.jpg",
			name:"小米9",
		},
		{
			url:"https://www.kauzhu.com",
			src:"img/p2.jpg",
			name:"小米9",
		}
	],
	[
		{
			url:"https://www.kauzhu.com",
			src:"img/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.kauzhu.com",
			src:"img/p2.jpg",
			name:"小米9"
		}
	],
	[
		{
			url:"https://www.kauzhu.com",
			src:"img/p1.jpg",
			name:"小米9",
		},
		{
			url:"https://www.kauzhu.com",
			src:"img/p2.jpg",
			name:"小米9",
		}
	],
	[
		{
			url:"https://www.kauzhu.com",
			src:"img/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.kauzhu.com",
			src:"img/p2.jpg",
			name:"小米9"
		}
	],
	[
		{
			url:"https://www.kauzhu.com",
			src:"img/p1.jpg",
			name:"小米9",
		},
		{
			url:"https://www.kauzhu.com",
			src:"img/p2.jpg",
			name:"小米9",
		}
	],
	[
		{
			url:"https://www.kauzhu.com",
			src:"img/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.kauzhu.com",
			src:"img/p2.jpg",
			name:"小米9"
		}
	],
	[
		{
			url:"https://www.kauzhu.com",
			src:"img/p1.jpg",
			name:"小米9",
		},
		{
			url:"https://www.kauzhu.com",
			src:"img/p2.jpg",
			name:"小米9",
		}
	],
	[
		{
			url:"https://www.kauzhu.com",
			src:"img/p1.jpg",
			name:"小米ma"
		},
		{
			url:"https://www.kauzhu.com",
			src:"img/p2.jpg",
			name:"小米ma"
		}
	],
]

/*
<li class="product-item">
	<a href="#">
		<img src="img/p1.jpg" alt="">
		<p class="product-item-name">小米9 6GB+128GB</p>
		<p class="product-item-dec">骁龙855，索尼4800万超广角微距三摄</p>
		<p class="product-item-price">
			<strong>3699元</strong>
		<del>4699元</del>
		</p>	
	</a>
	<span class="flage off-flage">减800元</span>
	<div class="views">
		<p class="commen">电视收到了，虽然有点晚但是质量还不错</p>
		<p class="author">评论来自于kauzhu</p>
	</div>
	</li>
*/

var elecDate =[
	[
		{
			url:"https:www.kauzhu.com",
			src:"img/p1.jpg",
			name:"小米9 6GB+128GB",
			des:"骁龙855，索尼4800万超广角微距三摄",
			price:3699,
			del:4999,
			flage:{
				class:"off-flage",
				name:"减800元",
			},
			views:{
				commen:"电视收到了，虽然有点晚但是质量还不错",
				author:"评论来自于kauzhu",
			}
		},
		{
			url:"https:www.kauzhu.com",
			src:"img/p1.jpg",
			name:"小米9 6GB+128GB",
			des:"骁龙855，索尼4800万超广角微距三摄",
			price:3699,
			del:4999,
			flage:{
				class:"off-flage",
				name:"减800元",
			},
			views:{
				commen:"电视收到了，虽然有点晚但是质量还不错",
				author:"评论来自于kauzhu",
			}
		},
		{
			url:"https:www.kauzhu.com",
			src:"img/p1.jpg",
			name:"小米9 6GB+128GB",
			des:"骁龙855，索尼4800万超广角微距三摄",
			price:3699,
			del:4999,
			flage:{
				class:"off-flage",
				name:"减800元",
			},
			views:{
				commen:"电视收到了，虽然有点晚但是质量还不错",
				author:"评论来自于kauzhu",
			}
		},
		{
			url:"https:www.kauzhu.com",
			src:"img/p1.jpg",
			name:"小米9 6GB+128GB",
			des:"骁龙855，索尼4800万超广角微距三摄",
			price:3699,
			del:4999,
			flage:{
				class:"off-flage",
				name:"减800元",
			},
			views:{
				commen:"电视收到了，虽然有点晚但是质量还不错",
				author:"评论来自于kauzhu",
			}
		},
		{
			url:"https:www.kauzhu.com",
			src:"img/p1.jpg",
			name:"小米9 6GB+128GB",
			des:"骁龙855，索尼4800万超广角微距三摄",
			price:3699,
			del:4999,
			flage:{
				class:"off-flage",
				name:"减800元",
			},
			views:{
				commen:"电视收到了，虽然有点晚但是质量还不错",
				author:"评论来自于kauzhu",
			}
		},
		{
			url:"https:www.kauzhu.com",
			src:"img/p1.jpg",
			name:"小米9 6GB+128GB",
			des:"骁龙855，索尼4800万超广角微距三摄",
			price:3699,
			del:4999,
			flage:{
				class:"off-flage",
				name:"减800元",
			},
			views:{
				commen:"电视收到了，虽然有点晚但是质量还不错",
				author:"评论来自于kauzhu",
			}
		},
		{
			url:"https:www.kauzhu.com",
			src:"img/p1.jpg",
			name:"小米9 6GB+128GB",
			des:"骁龙855，索尼4800万超广角微距三摄",
			price:3699,
			del:4999,
			flage:{
				class:"off-flage",
				name:"减800元",
			},
			views:{
				commen:"电视收到了，虽然有点晚但是质量还不错",
				author:"评论来自于kauzhu",
			}
		}
	],
	[
		{
			url:"https:www.kauzhu.com",
			src:"img/p2.jpg",
			name:"小米9 6GB+128GB",
			des:"骁龙855，索尼4800万超广角微距三摄",
			price:3699,
			del:4999,
			flage:{
				class:"off-flage",
				name:"减800元",
			},
			views:{
				commen:"电视收到了，虽然有点晚但是质量还不错",
				author:"评论来自于kauzhu",
			}
		},
		{
			url:"https:www.kauzhu.com",
			src:"img/p2.jpg",
			name:"小米9 6GB+128GB",
			des:"骁龙855，索尼4800万超广角微距三摄",
			price:3699,
			del:4999,
			flage:{
				class:"off-flage",
				name:"减800元",
			},
			views:{
				commen:"电视收到了，虽然有点晚但是质量还不错",
				author:"评论来自于kauzhu",
			}
		},
		{
			url:"https:www.kauzhu.com",
			src:"img/p2.jpg",
			name:"小米9 6GB+128GB",
			des:"骁龙855，索尼4800万超广角微距三摄",
			price:3699,
			del:4999,
			flage:{
				class:"off-flage",
				name:"减800元",
			},
			views:{
				commen:"电视收到了，虽然有点晚但是质量还不错",
				author:"评论来自于kauzhu",
			}
		},
		{
			url:"https:www.kauzhu.com",
			src:"img/p2.jpg",
			name:"小米9 6GB+128GB",
			des:"骁龙855，索尼4800万超广角微距三摄",
			price:3699,
			del:4999,
			flage:{
				class:"off-flage",
				name:"减800元",
			},
			views:{
				commen:"电视收到了，虽然有点晚但是质量还不错",
				author:"评论来自于kauzhu",
			}
		},
		{
			url:"https:www.kauzhu.com",
			src:"img/p2.jpg",
			name:"小米9 6GB+128GB",
			des:"骁龙855，索尼4800万超广角微距三摄",
			price:3699,
			del:4999,
			flage:{
				class:"off-flage",
				name:"减800元",
			},
			views:{
				commen:"电视收到了，虽然有点晚但是质量还不错",
				author:"评论来自于kauzhu",
			}
		},
		{
			url:"https:www.kauzhu.com",
			src:"img/p2.jpg",
			name:"小米9 6GB+128GB",
			des:"骁龙855，索尼4800万超广角微距三摄",
			price:3699,
			del:4999,
			flage:{
				class:"off-flage",
				name:"减800元",
			},
			views:{
				commen:"电视收到了，虽然有点晚但是质量还不错",
				author:"评论来自于kauzhu",
			}
		}
	],
	[
		{
			url:"https:www.kauzhu.com",
			src:"img/p1.jpg",
			name:"小米9 6GB+128GB",
			des:"骁龙855，索尼4800万超广角微距三摄",
			price:3699,
			del:4999,
			flage:{
				class:"off-flage",
				name:"减800元",
			},
			views:{
				commen:"电视收到了，虽然有点晚但是质量还不错",
				author:"评论来自于kauzhu",
			}
		},
		{
			url:"https:www.kauzhu.com",
			src:"img/p1.jpg",
			name:"小米9 6GB+128GB",
			des:"骁龙855，索尼4800万超广角微距三摄",
			price:3699,
			del:4999,
			flage:{
				class:"off-flage",
				name:"减800元",
			},
			views:{
				commen:"电视收到了，虽然有点晚但是质量还不错",
				author:"评论来自于kauzhu",
			}
		},
		{
			url:"https:www.kauzhu.com",
			src:"img/p1.jpg",
			name:"小米9 6GB+128GB",
			des:"骁龙855，索尼4800万超广角微距三摄",
			price:3699,
			del:4999,
			flage:{
				class:"off-flage",
				name:"减800元",
			},
			views:{
				commen:"电视收到了，虽然有点晚但是质量还不错",
				author:"评论来自于kauzhu",
			}
		},
		{
			url:"https:www.kauzhu.com",
			src:"img/p1.jpg",
			name:"小米9 6GB+128GB",
			des:"骁龙855，索尼4800万超广角微距三摄",
			price:3699,
			del:4999,
			flage:{
				class:"off-flage",
				name:"减800元",
			},
			views:{
				commen:"电视收到了，虽然有点晚但是质量还不错",
				author:"评论来自于kauzhu",
			}
		},
		{
			url:"https:www.kauzhu.com",
			src:"img/p1.jpg",
			name:"小米9 6GB+128GB",
			des:"骁龙855，索尼4800万超广角微距三摄",
			price:3699,
			del:4999,
			flage:{
				class:"off-flage",
				name:"减800元",
			},
			views:{
				commen:"电视收到了，虽然有点晚但是质量还不错",
				author:"评论来自于kauzhu",
			}
		},
		{
			url:"https:www.kauzhu.com",
			src:"img/p1.jpg",
			name:"小米9 6GB+128GB",
			des:"骁龙855，索尼4800万超广角微距三摄",
			price:3699,
			del:4999,
			flage:{
				class:"off-flage",
				name:"减800元",
			},
			views:{
				commen:"电视收到了，虽然有点晚但是质量还不错",
				author:"评论来自于kauzhu",
			}
		}
	],
	[
		{
			url:"https:www.kauzhu.com",
			src:"img/p2.jpg",
			name:"小米9 6GB+128GB",
			des:"骁龙855，索尼4800万超广角微距三摄",
			price:3699,
			del:4999,
			flage:{
				class:"off-flage",
				name:"减800元",
			},
			views:{
				commen:"电视收到了，虽然有点晚但是质量还不错",
				author:"评论来自于kauzhu",
			}
		},
		{
			url:"https:www.kauzhu.com",
			src:"img/p2.jpg",
			name:"小米9 6GB+128GB",
			des:"骁龙855，索尼4800万超广角微距三摄",
			price:3699,
			del:4999,
			flage:{
				class:"off-flage",
				name:"减800元",
			},
			views:{
				commen:"电视收到了，虽然有点晚但是质量还不错",
				author:"评论来自于kauzhu",
			}
		},
		{
			url:"https:www.kauzhu.com",
			src:"img/p2.jpg",
			name:"小米9 6GB+128GB",
			des:"骁龙855，索尼4800万超广角微距三摄",
			price:3699,
			del:4999,
			flage:{
				class:"off-flage",
				name:"减800元",
			},
			views:{
				commen:"电视收到了，虽然有点晚但是质量还不错",
				author:"评论来自于kauzhu",
			}
		}
	]

]